### ISSUE TITLE
AutodeskCAD 2014 can not open dxf

### ISSUE THREAD

**Issue by Yaxian** [aspose-cad/Aspose.CAD-for-Java#5]
Hello, 
I wanna try transfer dwg to dxf. 

I try to open `Examples/src/main/resources/DWGDrawings/Line.dxf` by `Autodesk CAD 2014`.
It did work.

```
The unknown header value $ LASTSAVEDBY line 10 has been ignored.
The unknown header value $ _3DDWFPREC line 914 has been ignored.
There is an error in the VPORT table
The object ends early at line 1130.
DXF input is invalid or incomplete-the graphic was discarded.
```

**Comment by OleksiiGor** [comment]
Hello, we hope now export to DXF is better, you may try our latest releases: https://downloads.aspose.com/cad/java
